In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [7]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
oh_rep = [one_hot(words,voc_size)for words in sent]

In [6]:
oh_rep

[[3057, 5929, 1739, 7447],
 [3057, 5929, 1739, 3820],
 [3057, 1452, 1739, 1333],
 [1519, 7462, 5256, 7410, 7619],
 [1519, 7462, 5256, 7410, 5780],
 [9958, 3057, 8134, 1739, 7158],
 [4176, 7425, 8121, 7410]]

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_len = 8
embedded_docs = pad_sequences(oh_rep, padding = 'pre',maxlen=sent_len)
embedded_docs

array([[   0,    0,    0,    0, 3057, 5929, 1739, 7447],
       [   0,    0,    0,    0, 3057, 5929, 1739, 3820],
       [   0,    0,    0,    0, 3057, 1452, 1739, 1333],
       [   0,    0,    0, 1519, 7462, 5256, 7410, 7619],
       [   0,    0,    0, 1519, 7462, 5256, 7410, 5780],
       [   0,    0,    0, 9958, 3057, 8134, 1739, 7158],
       [   0,    0,    0,    0, 4176, 7425, 8121, 7410]], dtype=int32)

In [12]:
#feature representation
dim = 10

In [13]:

model = Sequential()
model.add(Embedding(voc_size, dim ,input_length = sent_len))
model.compile('adam','mse') 


c:\Users\user\OneDrive\Desktop\D.S. Udemy\Projects Deep Learning\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[[ 0.02575512, -0.02513089,  0.04657007,  0.0238804 ,
         -0.01650732, -0.00380161, -0.01078857,  0.01957988,
          0.03837598,  0.04807884],
        [ 0.02575512, -0.02513089,  0.04657007,  0.0238804 ,
         -0.01650732, -0.00380161, -0.01078857,  0.01957988,
          0.03837598,  0.04807884],
        [ 0.02575512, -0.02513089,  0.04657007,  0.0238804 ,
         -0.01650732, -0.00380161, -0.01078857,  0.01957988,
          0.03837598,  0.04807884],
        [ 0.02575512, -0.02513089,  0.04657007,  0.0238804 ,
         -0.01650732, -0.00380161, -0.01078857,  0.01957988,
          0.03837598,  0.04807884],
        [-0.00052977, -0.0255072 , -0.01706789,  0.02348112,
         -0.00777155,  0.02415574, -0.03578804,  0.03255144,
          0.0268829 ,  0.01711923],
        [-0.03060404,  0.03953186,  0.02750045, -0.02852926,
          0.02191237,  0.03157271, -0.02728965,  0.00856247,
          0.02172152, -0.04804868],
        [-0.00954405, -0.00441407,  0.03102433,  0.0

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
embedded_docs[0] 

array([   0,    0,    0,    0, 3057, 5929, 1739, 7447], dtype=int32)

In [ ]:
model.predict(embedded_docs)[0] #. 10 features for each word in the first sentence

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[ 0.02575512, -0.02513089,  0.04657007,  0.0238804 , -0.01650732,
        -0.00380161, -0.01078857,  0.01957988,  0.03837598,  0.04807884],
       [ 0.02575512, -0.02513089,  0.04657007,  0.0238804 , -0.01650732,
        -0.00380161, -0.01078857,  0.01957988,  0.03837598,  0.04807884],
       [ 0.02575512, -0.02513089,  0.04657007,  0.0238804 , -0.01650732,
        -0.00380161, -0.01078857,  0.01957988,  0.03837598,  0.04807884],
       [ 0.02575512, -0.02513089,  0.04657007,  0.0238804 , -0.01650732,
        -0.00380161, -0.01078857,  0.01957988,  0.03837598,  0.04807884],
       [-0.00052977, -0.0255072 , -0.01706789,  0.02348112, -0.00777155,
         0.02415574, -0.03578804,  0.03255144,  0.0268829 ,  0.01711923],
       [-0.03060404,  0.03953186,  0.02750045, -0.02852926,  0.02191237,
         0.03157271, -0.02728965,  0.00856247,  0.02172152, -0.04804868],
       [-0.00954405, -0.00441407,  0.03102433,  0.01468161,  0.0484717 ,
        -0.02587789,  0.04645375, -0.01395677